on:
  push:

jobs:
  update_pot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install -r requirements/release.txt
          # temporarily use master version as not yet released
          python -m pip install git+https://github.com/jupyterlab/jupyterlab-translate
      - name: Update po templates
        run: |
          python scripts/02_update_catalogs.py
      - name: Set branch name
        run: echo "BRANCH_NAME=pot-update-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Create a new branch
        run: |
          git checkout -b "${{ env.BRANCH_NAME }}"
      - name: Set up git identity
        run: |
          git config user.name "JupyterLab Language Packs Bot"
          git config --global user.email 'krassowski@users.noreply.github.com'
      - name: Commit changes
        run: |
          git add *.pot
          git commit -m "Update pot files"
      - name: Push the changes
        run: |
          git push --set-upstream origin "${{ env.BRANCH_NAME }}"
      - name: Create a PR
        run: |
          hub pull-request -m "Update pot files"
        env:
          GITHUB_USER: jupyterlab-bot
